/**
 * 用到的 Material Symbols 圖示名稱。
 * 只下載這裡列出的圖示（vite.config.ts 會依這份清單組出字型網址），
 * 新增圖示時記得加在這裡，否則會顯示成文字。
 */
export const ICON_NAMES = [
  'add',
  'arrow_back',
  'arrow_forward',
  'auto_awesome',
  'balance',
  'bolt',
  'calendar_month',
  'celebration',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'content_copy',
  'content_paste',
  'cookie',
  'dark_mode',
  'directions_walk',
  'eco',
  'edit',
  'egg',
  'error',
  'event_available',
  'favorite',
  'fitness_center',
  'groups',
  'history',
  'home',
  'info',
  'kitchen',
  'lightbulb',
  'local_fire_department',
  'lock',
  'menu_book',
  'monitor_weight',
  'new_releases',
  'nutrition',
  'open_in_new',
  'person',
  'refresh',
  'remove',
  'restaurant',
  'schedule',
  'search',
  'sentiment_satisfied',
  'shopping_basket',
  'shopping_cart',
  'skillet',
  'spa',
  'star',
  'swap_vert',
  'sync',
  'system_update',
  'task_alt',
  'timer',
  'touch_app',
  'trending_down',
  'trending_flat',
  'trending_up',
  'warning',
  'water_drop',
  'waving_hand',
  'wb_sunny',
  'wb_twilight',
] as const

export type IconName = (typeof ICON_NAMES)[number]
